services:
  fastapi-auth-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fastapi-auth-app-service
    hostname: fastapi-auth-app-service
    ports:
      - "8000:8000"
    volumes:
      - ./:/code
    environment:
      - DATABASE_URL=bolt://neo4j:test1234@fastapi-neo4j-db-service:7687
      - SECRET_KEY=tu-clave-secreta-aqui
      - DEBUG=True
    depends_on:
      - fastapi-auth-neo4j:
          condition: service_healthy

  fastapi-auth-neo4j:
    image: neo4j:2025.06
    container_name: fastapi-neo4j-db-service
    hostname: fastapi-neo4j-db-service
    ports:
      - "7474:7474" 
      - "7687:7687" 
    environment:
      - NEO4J_AUTH=neo4j/test1234
      - NEO4J_apoc_export_file_enabled=true
      - NEO4J_apoc_import_file_enabled=true
      - NEO4J_apoc_import_file_use__neo4j__config=true
      - NEO4J_dbms_security_procedures_unrestricted=apoc.*
      - NEO4J_dbms_security_procedures_allowlist=apoc.*
    volumes:
      - neo4j_data:/data
      - ./plugins:/plugins
    healthcheck:
      test: ["CMD", "cypher-shell", "-u", "neo4j", "-p", "test1234", "RETURN 1"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  neo4j_data: